FROM node:18-alpine AS build
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./
RUN npm ci --only=production

# Copiar archivos estáticos
COPY public ./public
COPY server.js .

EXPOSE 3000

CMD ["node", "server.js"]